POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RpIiwiaWQiOiI2M2QxODlmNzcwNTRlOWZkZmMwMmE1NDYiLCJpYXQiOjE2NzQ5MzMxNjd9.MYzMNymJlptbvnjWHTvkRVQK4SObh_Tw7iVuVVqJFCE

{
    "title": "Kokeile lisätä4",
    "author": "Koe Foe",
    "url": "https://osoite.on.nelkku",
    "likes": 1
}